/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi_hk;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DM_spJPanel extends javax.swing.JPanel {
    List<DM_sp> DM_spList = new ArrayList<>();
    DefaultTableModel tableModel;
    private Connection con = null;
    public DM_spJPanel() throws SQLException {
        initComponents();
        tableModel = (DefaultTableModel) tblDMllist.getModel();
        LoadDatabase();
        showAll();
        tblDMllist.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int index = tblDMllist.getSelectedRow();
                DM_sp dm = DM_spList.get(index);
                txtTenDM.setText(dm.getTenDM());
                btnsua.setEnabled(true);
                btnxoa.setEnabled(true);
            }

            @Override
            public void mousePressed(MouseEvent e) {
          
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            
            }

            @Override
            public void mouseEntered(MouseEvent e) {
               
            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
    }
    private void  showAll(){
        tableModel.setRowCount(0);
        for (int i = 0; i < DM_spList.size(); i++) {
            tableModel.addRow(new String[]{
                String.valueOf(DM_spList.get(i).getId()),
                DM_spList.get(i).getTenDM()
        });
        }
    }
    private void  LoadDatabase() throws SQLException{
        DM_spList.clear();
        String url = "net.sourceforge.jtds.jdbc.Driver";
        Statement statement = null;
        try {
            Class.forName(url);
            String dbUrl = "jdbc:jtds:sqlserver://DAUCONG:1433/BanDoAnVat";
            con = (Connection) DriverManager.getConnection(dbUrl);
            String sql = "select * from Danhmuc_sp";
            statement = con.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                DM_sp dm_sp = new DM_sp(rs.getInt("id"), rs.getString("TenDM"));
                DM_spList.add(dm_sp);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            if(statement !=null){
                try {
                    statement .close();
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(con !=null){
                con.close();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Danhmuc_sp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDM = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDMllist = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Danhmuc_sp.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập thông tin danh mục"));

        jLabel1.setText("Tên danh mục:");

        btnthem.setBackground(new java.awt.Color(204, 204, 204));
        btnthem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thi_hk/chucnang/add-button (1).png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(204, 204, 204));
        btnsua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thi_hk/chucnang/refresh (3).png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.setEnabled(false);
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(204, 204, 204));
        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thi_hk/chucnang/delete (2).png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.setEnabled(false);
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnthem)
                        .addGap(47, 47, 47)
                        .addComponent(btnsua)
                        .addGap(63, 63, 63)
                        .addComponent(btnxoa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTenDM, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        tblDMllist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TenDM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDMllist);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("DANH MỤC SẢN PHẨM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Danhmuc_spLayout = new javax.swing.GroupLayout(Danhmuc_sp);
        Danhmuc_sp.setLayout(Danhmuc_spLayout);
        Danhmuc_spLayout.setHorizontalGroup(
            Danhmuc_spLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Danhmuc_spLayout.setVerticalGroup(
            Danhmuc_spLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Danhmuc_spLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Danhmuc_sp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Danhmuc_sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed

            // TODO add your handling code here:
            String tenDM = txtTenDM.getText().toString();
            if(tenDM.isEmpty()){
                JOptionPane.showMessageDialog(this, "Nhập tên danh mục cần thêm");
            }else{
                try {
                    insert(tenDM);
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            txtTenDM.setText("");
        try {
            LoadDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            showAll();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int index = tblDMllist.getSelectedRow();
        DM_sp dm = DM_spList.get(index);
        String url = "net.sourceforge.jtds.jdbc.Driver";
        PreparedStatement preparedStatement = null;
        try {
            Class.forName(url);
            String dbUrl = "jdbc:jtds:sqlserver://DAUCONG:1433/BanDoAnVat";
            con = (Connection) DriverManager.getConnection(dbUrl);
            String sql = "delete from DanhMuc_sp where id = ?";
            preparedStatement = con.prepareStatement(sql);
            preparedStatement.setInt(1, dm.getId());
            preparedStatement.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            if(preparedStatement !=null){
                try {
                    preparedStatement .close();
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(con !=null){
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        try {
            LoadDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            showAll();
            txtTenDM.setText("");
            btnxoa.setEnabled(false);
            btnsua.setEnabled(false);
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        int index = tblDMllist.getSelectedRow();
        DM_sp dm = DM_spList.get(index);
        String url = "net.sourceforge.jtds.jdbc.Driver";
        PreparedStatement preparedStatement = null;
        try {
            Class.forName(url);
            String dbUrl = "jdbc:jtds:sqlserver://DAUCONG:1433/BanDoAnVat";
            con = (Connection) DriverManager.getConnection(dbUrl);
            String sql = "update DanhMuc_sp set TenDM=?" + " where id = ?";
            preparedStatement = con.prepareStatement(sql);
            preparedStatement.setString(1, txtTenDM.getText().toString());
             preparedStatement.setInt(2, dm.getId());
            preparedStatement.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            if(preparedStatement !=null){
                try {
                    preparedStatement .close();
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(con !=null){
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        try {
            LoadDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            showAll();
            txtTenDM.setText("");
            btnxoa.setEnabled(false);
            btnsua.setEnabled(false);
    }//GEN-LAST:event_btnsuaActionPerformed
    private void insert (String TenDM) throws SQLException{

        String url = "net.sourceforge.jtds.jdbc.Driver";
        PreparedStatement preparedStatement = null;
        try {
            Class.forName(url);
            String dbUrl = "jdbc:jtds:sqlserver://DAUCONG:1433/BanDoAnVat";
            con = (Connection) DriverManager.getConnection(dbUrl);
            String sql = "insert into DanhMuc_sp(TenDM) values (?)";
            preparedStatement = con.prepareStatement(sql);
            preparedStatement.setString(1, TenDM);
            preparedStatement.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            if(preparedStatement !=null){
                try {
                    preparedStatement .close();
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(con !=null){
                con.close();
            }
        }
    }
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DM_spJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DM_spJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DM_spJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DM_spJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DM_spJPanel().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DM_spJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Danhmuc_sp;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDMllist;
    private javax.swing.JTextField txtTenDM;
    // End of variables declaration//GEN-END:variables
}
